### ISSUE TITLE
发送图片时错误

### ISSUE THREAD

**Issue by 5656565566** [JustUndertaker/ComWeChatBotClient#37]
08-01 23:12:09 [SUCCESS] wechatbot_client | OneBot V12 | 收到action请求: {'action': 'upload_file', 'params': {'type': 'data', 'name': 'p.png', 'data': '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2...
08-01 23:12:09 [SUCCESS] wechatbot_client | OneBot V12 | 收到action请求: {'action': 'send_message', 'params': {'detail_type': 'private', 'user_id': 'wxid_179w644fpwie22', 'message': [{'type': 'image', 'data': {'file_id': {'file_id': '32803555-d96a-4330-9918-8a588c99724e'}}...
08-01 23:12:09 [ ERROR ] wechatbot_client | Action Manager | 发送消息出错
Traceback (most recent call last):
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\main.py", line 9, in <module>
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\__init__.py", line 35, in run
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\driver\driver.py", line 134, in run
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\uvicorn\main.py", line 569, in run
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\uvicorn\server.py", line 60, in run
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\asyncio\runners.py", line 44, in run
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\asyncio\base_events.py", line 636, in run_until_complete
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\asyncio\windows_events.py", line 321, in run_forever
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\asyncio\base_events.py", line 603, in run_forever
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\asyncio\base_events.py", line 1909, in _run_once
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\asyncio\events.py", line 80, in _run
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\wechat\adapter.py", line 275, in _backward_ws
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\wechat\wechat.py", line 130, in action_ws_request
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\wechat\wechat.py", line 110, in action_request
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\action_manager\manager.py", line 159, in request
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\action_manager\manager.py", line 294, in send_message
> File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\action_manager\manager.py", line 363, in _send_private_msg
  File "C:\Users\BOTSER~1\AppData\Local\Temp\ONEFIL~1\wechatbot_client\action_manager\manager.py", line 195, in _send_image
TypeError: cannot unpack non-iterable NoneType object

**Comment by 2269961201** [comment]
解决了吗。我也发不了图片
